Repository liferay/com-liferay-commerce, pull requests merged in 2019-05, with the labels that each got.

#836 COMMERCE-1361 Using aui-base will ensure the A.one won't be used before AUI is loaded
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition/details.jsp
Labels: ci:test - failure

#833 COMMERCE-1343 | 7.1.x-next - Remove deployment dependency of Jackson
  commerce-openapi-core-impl/build.gradle
Labels: ci:test - failure

#830 COMMERCE-1351 Show hidden pages in Product Display Page configuration
  commerce-product-definitions-web/build.gradle
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/display/context/CPDefinitionsDisplayContext.java
Labels: ci:test - failure

#822 COMMERCE-1308 Allow users to set product's low stock action to null
  commerce-inventory-web/src/main/resources/META-INF/resources/edit_definition_inventory.jsp
Labels: ci:test - success

#821 COMMERCE-149 Fix Terms of Use panel
  commerce-product-type-virtual-web/src/main/resources/META-INF/resources/definition_virtual_setting/terms_of_use.jsp
  commerce-product-type-virtual-web/src/main/resources/META-INF/resources/terms_of_use.jspf
Labels: ci:test - failure

#813 COMMERCE-686 fix product gallery ratio
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/components/minium-product-gallery.scss
Labels: ci:test - success

#811 EMP-25 Breccia Images should open in modal
  commerce-initializer-breccia/src/main/resources/META-INF/resources/render/view.jsp
Labels: ci:test - success

#808 COMMERCE-1196 Set checkoutURL even when order is null
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/MiniCartTag.java
Labels: ci:test - success

#773 COMMERCE-1246 Make zip a required model field
  commerce-service/src/main/resources/META-INF/portlet-model-hints.xml
Labels: ci:test - success

#778 COMMERCE-935 Only show cancel button if backURL exists
  commerce-account-web/src/main/resources/META-INF/resources/edit_user.jsp
Labels: ci:test - success

#845 COMMERCE-686 Auto SF
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/cart/CommerceCartResource.java
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/components/add-to-cart-button.scss
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/components/commerce-cart-item.scss
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/components/commerce-quantity-selector.scss
Labels: ci:test - success

#837 COMMERCE-1362 Since we need assetLinkEntryIds lets use those instead of assetLinkIds for updating links
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPDefinitionMVCActionCommand.java
Labels: ci:test - success

#847 COMMERCE-1374 commerce-product-service Preserve parameters when gener…
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/CPDefinitionHelperImpl.java
Labels: ci:test - success

#848 COMMERCE-1381 Fix jsp's path and render command's name
  commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/portlet/action/ViewCommerceOrderNotesMVCRenderCommand.java
  commerce-order-content-web/src/main/resources/META-INF/resources/placed_orders/view_order_details.jsp
Labels: ci:test - failure

#855 LPS-84119 Auto SF
  commerce-notification-service/src/main/java/com/liferay/commerce/notification/service/impl/CommerceNotificationQueueEntryLocalServiceImpl.java
  commerce-product-api/src/main/java/com/liferay/commerce/product/catalog/CPQuery.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/util/CPPublisherWebHelper.java
  commerce-product-options-web/src/main/resources/META-INF/resources/edit_option_value.jsp
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/CPDefinitionSearcher.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/model/impl/CPDefinitionImpl.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/search/CPDefinitionOptionRelIndexer.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/search/CPOptionIndexer.java
  commerce-product-type-virtual-test-util/src/main/java/com/liferay/commerce/product/type/virtual/test/util/VirtualCPTypeTestUtil.java
Labels: ci:test - success

#857 COMMERCE-1390 Fix Order Table messages (from Steven)
  commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/frontend/util/CommerceOrderClayTableUtil.java
Labels: ci:test - success

#854 COMMERCE-1292 Prevent xss on price
  commerce-product-content-web/src/main/resources/META-INF/resources/js/product_content.js
Labels: ci:test - success

#853 COMMERCE-1287 Prevent XSS on some sku outputs
  commerce-product-content-web/src/main/resources/META-INF/resources/js/product_content.js
  commerce-product-type-simple/src/main/resources/META-INF/resources/render/list_entry/compare_product.jsp
Labels: ci:test - success

#852 COMMERCE-1393 Fix pagination issue with persisting selected definition links
  commerce-product-item-selector-web/src/main/java/com/liferay/commerce/product/item/selector/web/internal/display/context/CPDefinitionItemSelectorViewDisplayContext.java
  commerce-product-item-selector-web/src/main/resources/META-INF/resources/definition_item_selector.jsp
Labels: ci:test - success

#861 Fix CI issues
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CommerceUsersImporter.java
  commerce-openapi-admin/src/main/java/com/liferay/commerce/openapi/admin/internal/resource/util/v1_0/UserHelper.java
  commerce-openapi-admin/src/main/java/com/liferay/commerce/openapi/admin/internal/resource/util/v2_0/UserHelper.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/Method.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/generator/OSGiRESTModuleGenerator.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/generator/ParameterGenerator.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/importer/ComponentImporter.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/importer/ParameterImporter.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/util/GetterUtil.java
  commerce-openapi-util/src/test/java/com/liferay/commerce/openapi/util/generator/DTOGeneratorTest.java
  commerce-openapi-util/src/test/java/com/liferay/commerce/openapi/util/generator/ResourceGeneratorTest.java
  commerce-openapi-util/src/test/java/com/liferay/commerce/openapi/util/importer/FileOpenApiReaderTest.java
Labels: ci:test - pending

#860 LPS-91413
  commerce-product-definitions-web/bnd.bnd
Labels: ci:test - pending

#868 COMMERCE-1401 Fixed add to cart tag
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddToCartTag.java
Labels: ci:test - pending

#878 EMP-28 Use commerce account id instead of user id
  commerce-product-type-virtual-order-content-web/build.gradle
  commerce-product-type-virtual-order-content-web/src/main/java/com/liferay/commerce/product/type/virtual/order/content/web/internal/display/context/CommerceVirtualOrderItemContentDisplayContext.java
  commerce-product-type-virtual-order-content-web/src/main/java/com/liferay/commerce/product/type/virtual/order/content/web/internal/portlet/CommerceVirtualOrderItemContentPortlet.java
  commerce-product-type-virtual-order-content-web/src/main/java/com/liferay/commerce/product/type/virtual/order/content/web/internal/portlet/action/CommerceVirtualOrderItemContentConfigurationAction.java
  commerce-product-type-virtual-order-content-web/src/main/java/com/liferay/commerce/product/type/virtual/order/content/web/internal/portlet/action/ViewCommerceVirtualOrderItemTermsOfUseMVCRenderCommand.java
Labels: ci:test - success

#867 COMMERCE-1409
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountClayTable.java
Labels: ci:test - success

#882 LPS-94365 Use latest arquillian version
  commerce-account-test/build.gradle
  commerce-currency-test/build.gradle
  commerce-discount-test/build.gradle
  commerce-notification-test/build.gradle
  commerce-payment-test/build.gradle
  commerce-price-list-test/build.gradle
  commerce-product-test/build.gradle
  commerce-product-type-grouped-test/build.gradle
  commerce-product-type-virtual-order-test/build.gradle
  commerce-product-type-virtual-test/build.gradle
  commerce-shipping-engine-fixed-test/build.gradle
  commerce-tax-engine-fixed-test/build.gradle
  commerce-tax-test/build.gradle
  commerce-test/build.gradle
  commerce-user-segment-test/build.gradle
  commerce-wish-list-test/build.gradle
Labels: ci:test - pending

#905 Multi site catalog sf fixes
  commerce-catalog-web/bnd.bnd
  commerce-catalog-web/src/main/resources/META-INF/resources/details.jsp
  commerce-catalog-web/src/main/resources/com/liferay/commerce/catalog/web/display/context/packageinfo
  commerce-channel-web/build.gradle
  commerce-channel-web/src/main/java/com/liferay/commerce/channel/web/display/context/BaseCommerceChannelDisplayContext.java
  commerce-channel-web/src/main/java/com/liferay/commerce/channel/web/display/context/BaseCommerceChannelSearchContainerDisplayContext.java
  commerce-channel-web/src/main/java/com/liferay/commerce/channel/web/internal/display/context/CommerceChannelDisplayContext.java
  commerce-channel-web/src/main/java/com/liferay/commerce/channel/web/internal/portlet/action/EditCommerceChannelMVCActionCommand.java
  commerce-channel-web/src/main/resources/META-INF/resources/details.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_columns.jspf
  source-formatter-suppressions.xml
Labels: ci:test - pending

#919 COMMERCE-682 Wide layouts allowed
  commerce-theme-minium/commerce-theme-minium/src/WEB-INF/liferay-look-and-feel.xml
  commerce-theme-minium/commerce-theme-minium/src/templates/init_custom.ftl
  commerce-theme-minium/commerce-theme-minium/src/templates/portal_normal.ftl
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/components/minium-content.scss
Labels: ci:test - failure

#926 COMMERCE-686 Notifications + Account selector image fixes
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCartButton.es.js
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/components/commerce-account-selector.scss
Labels: ci:test - failure

#898 COMMERCE-1436 commerce-service Add new fields to the OrderItemIndexer
  commerce-service/src/main/java/com/liferay/commerce/internal/search/CommerceOrderItemIndexer.java
Labels: ci:test - failure
