Repository liferay/com-liferay-commerce, pull requests merged in 2019-02, with the labels that each got.

#508 LRQA-46140 Fix test to only run when necessary (backport)
  commerce-product-test/src/testFunctional/tests/CommerceAdmin.testcase
Labels: ci:test - pending

#509 COMMERCE-787 Fix 'End After' field staying hidden after multiple toggles
  commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_definition_subscription_info.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_instance_subscription_info.jsp
  commerce-subscription-web/src/main/resources/META-INF/resources/subscription_entry/details.jsp
Labels: ci:test - pending

#462 COMMERCE-0 Source formatting for commerce-frontend-taglib
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AccountSelectorTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddAccountModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddAddressModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddOrganizationsModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddToCartTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/CommerceTableTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/MiniCartTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/PriceTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/ProductDetailsModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/QuantitySelectorTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/SearchBarTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/SearchResultsTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/UserInvitationModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/UserRolesModalTag.java
  commerce-frontend-taglib/src/main/resources/META-INF/liferay-commerce-ui.tld
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountSelector.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountsTable.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountsTableItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/OrdersTable.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_account_modal/AddAccountModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_account_modal/__AddAccountModal.es.js.or
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_address_modal/AddAddressModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_organizations_modal/AddOrganizationsModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_organizations_modal/OrganizationInputItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_organizations_modal/OrganizationListItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCartButton.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_tick_item/AddToTickItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/autocomplete_item/AutocompleteItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/clay_table/CommerceTable.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/input_utils/CommerceInputText.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/Cart.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/CartProduct.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/Loader.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/Summary.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/price/Price.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/product_details_modal/ProductDetailsModal.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/quantity_selector/QuantitySelector.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/search_bar/SearchBar.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/search_results/SearchResults.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_invitation_modal/UserInvitationModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_roles_modal/RoleInputItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_roles_modal/RoleListItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_roles_modal/UserRolesModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_utils/UserInputItem.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_utils/UserInvitation.es.js
Labels: ci:test - pending

#522 COMMERCE-928
  commerce-openapi-admin/src/main/java/com/liferay/commerce/openapi/admin/internal/application/CommerceOpenApiAdminApplication.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/context/provider/CompanyContextProvider.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/context/provider/LocaleContextProvider.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/context/provider/PaginationContextProvider.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/context/provider/PermissionCheckerContextProvider.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/context/provider/SortContextProvider.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/context/provider/ThemeDisplayContextProvider.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/context/provider/UserContextProvider.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/exception/GeneralExceptionMapper.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/exception/NoSuchUserExceptionMapper.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/exception/PrincipalExceptionMapper.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/exception/SystemExceptionMapper.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/jaxrs/json/JsonMessageBodyReader.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/jaxrs/json/JsonMessageBodyWriter.java
Labels: ci:test - failure

#529 COMMERCE-774 COMMERCE-778 Build service
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/http/CPRuleServiceHttp.java
Labels: ci:test - pending

#536 COMMERCE-686 Check for account permissions
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/display/context/BaseCommerceAccountDisplayContext.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/display/context/CommerceAccountAddressesDisplayContext.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/display/context/CommerceAccountDisplayContext.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountAddressClayTable.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountOrganizationClayTable.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountUserClayTable.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/servlet/taglib/ui/CommerceAccountAddressesScreenNavigationEntry.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/servlet/taglib/ui/CommerceAccountMembersScreenNavigationEntry.java
  commerce-account-web/src/main/resources/META-INF/resources/init.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view_account.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view_account_addresses.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view_account_info.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view_account_list.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view_account_members.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view_user.jsp
Labels: ci:test - failure

#539 COMMERCE-0 fix quantity selector when there are no allowerdOrderQuant…
  commerce-taglib/src/main/resources/META-INF/resources/quantity_input/init.jsp
  commerce-taglib/src/main/resources/META-INF/resources/quantity_input/page.jsp
Labels: ci:test - pending

#545 COMMERCE-774 Switch to new display context
  commerce-account-web/src/main/resources/META-INF/resources/view_account_addresses.jsp
Labels: ci:test - pending

#543 COMMERCE-958
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/jaxrs/xml/XMLMessageBodyWriter.java
Labels: ci:test - success

#548 COMMERCE-686 Add necessary compile-time dependency
  commerce-account-test/build.gradle
Labels: ci:test - failure

#551 COMMERCE-0 Use upsert method for upsert API
  commerce-openapi-admin/src/main/java/com/liferay/commerce/openapi/admin/internal/resource/v1_0/ProductResourceImpl.java
  commerce-openapi-admin/src/main/java/com/liferay/commerce/openapi/admin/internal/resource/v2_0/ProductResourceImpl.java
Labels: ci:test - success

#556 LPS-84119 Auto SF
  commerce-cart-taglib/bnd.bnd
  commerce-frontend-taglib/bnd.bnd
  commerce-product-taglib/bnd.bnd
  commerce-taglib/bnd.bnd
Labels: ci:test - success

#557 COMMERCE-1016 Avoid IOOBE in unusual cases
  commerce-account-web/src/main/resources/META-INF/resources/view.jsp
Labels: ci:test - pending

#562 COMMERCE-984
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/MiniCart.es.js
Labels: ci:test - pending

#561 COMMERCE-1000 Use right category
  commerce-wish-list-web/src/main/java/com/liferay/commerce/wish/list/web/internal/portlet/CommerceWishListPortlet.java
Labels: ci:test - pending

#563 COMMERCE-934 add to cart and compare conflict resolved
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCartButton.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCartButton.soy
Labels: ci:test - success

#571 COMMERCE-951 click on mini cart children handled
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/MiniCart.es.js
Labels: ci:test - pending

#577 COMMERCE-870 Source formatting
  commerce-frontend-api/src/main/java/com/liferay/commerce/frontend/model/ProductSettingsModel.java
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/util/ProductHelperImpl.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/internal/util/ProductHelperProvider.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddToCartTag.java
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCartButton.es.js
Labels: ci:test - success

#583 COMMERCE-1046 Index zip as text instead of number
  commerce-service/src/main/java/com/liferay/commerce/internal/search/CommerceAddressIndexer.java
Labels: ci:test - pending

#595 COMMERCE-872 Update JS module versions
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rels.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/toolbar.jsp
  commerce-product-options-web/src/main/resources/META-INF/resources/view.jsp
Labels: ci:test - success

#604 COMMERCE-1085 - 7.1.x-next
  commerce-openapi-core-impl/build.gradle
Labels: ci:test - success
