Repository liferay/com-liferay-commerce, pull requests merged in 2019-07, with the labels that each got.

#1095 COMMERCE-1567 Re-add removed Parent Price List button
  commerce-price-list-web/src/main/resources/META-INF/resources/price_list/details.jsp
Labels: ci:test - failure

#1112 COMMERCE-1592 Fixed Product Publisher
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/display/context/CPPublisherConfigurationDisplayContext.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/display/context/CPPublisherDisplayContext.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/portlet/action/CPPublisherConfigurationAction.java
  commerce-product-content-web/src/main/resources/META-INF/resources/product_publisher/configuration/filter.jsp
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java
Labels: ci:test - success

#1115 COMMERCE-1519 Fix rebase
  commerce-order-content-web/build.gradle
Labels: ci:test - pending

#949 COMMERCE-1463 Fix licensing issues/ambiguities
  commerce-theme-minium/commerce-theme-minium/src/WEB-INF/liferay-plugin-package.properties
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/account-selector/package.json
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/add-to-cart/package.json
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/minium-product-gallery/package.json
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/minium-search-bar/package.json
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/minium-search-results/package.json
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/minium-table/package.json
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/user-invitation/package.json
  commerce-theme-speedwell/commerce-theme-speedwell/src/WEB-INF/liferay-plugin-package.properties
  headless/headless-commerce/headless-commerce-admin-account-impl/rest-openapi.yaml
  headless/headless-commerce/headless-commerce-admin-catalog-impl/rest-openapi.yaml
  headless/headless-commerce/headless-commerce-admin-pricing-impl/rest-openapi.yaml
  headless/headless-commerce/headless-commerce-admin-site-setting-impl/rest-openapi.yaml
Labels: ci:test - failure

#1119 COMMERCE-1558 Fixed commerce search resource
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/search/CommerceSearchResource.java
Labels: ci:test - success

#1125 COMMERCE-1266 search bar can be invoked while a modal is open
  commerce-frontend-taglib/src/main/resources/META-INF/resources/search_bar/SearchBar.es.js
Labels: ci:test - failure

#1134 COMMERCE-1484 Fixed sku resource implementation
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/SkuResourceImpl.java
Labels: ci:test - failure

#1133 COMMERCE-1505 Fixed product dto converter
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/converter/ProductDTOConverter.java
Labels: ci:test - success

#1123 COMMERCE-1309 Fixed simple site item selector
  commerce-item-selector-web/src/main/java/com/liferay/commerce/item/selector/web/internal/display/context/SimpleSiteItemSelectorViewDisplayContext.java
Labels: ci:test - failure

#1154 COMMERCE-1594 Wrap persistence calls in transaction invoker
  commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountLocalServiceImpl.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CommerceCatalogLocalServiceImpl.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CommerceChannelLocalServiceImpl.java
Labels: ci:test - pending

#1178 COMMERCE-1637 Fixed commerce discount upgrade process
  commerce-discount-service/src/main/java/com/liferay/commerce/discount/internal/upgrade/CommerceDiscountUpgradeStepRegistrator.java
  commerce-discount-service/src/main/java/com/liferay/commerce/discount/internal/upgrade/base/BaseCommerceDiscountUpgradeProcess.java
  commerce-discount-service/src/main/java/com/liferay/commerce/discount/internal/upgrade/v2_1_0/CommerceDiscountExternalReferenceCodeUpgradeProcess.java
Labels: ci:test - success

#1197 LPS-98024 Auto SF
  headless/headless-commerce/headless-commerce-admin-account-impl/rest-openapi.yaml
  headless/headless-commerce/headless-commerce-admin-catalog-impl/rest-openapi.yaml
  headless/headless-commerce/headless-commerce-admin-pricing-impl/rest-openapi.yaml
  headless/headless-commerce/headless-commerce-admin-site-setting-impl/rest-openapi.yaml
Labels: ci:test - pending

#1198 COMMERCE-1463 Remove fake copyright statements
  commerce-theme-minium/commerce-theme-minium-site-initializer/src/main/resources/com/liferay/commerce/theme/minium/site/initializer/internal/dependencies/theme-settings.json
  commerce-theme-speedwell/commerce-theme-speedwell/src/templates/portal_normal.ftl
Labels: ci:test - success

#1190 COMMERCE-1651 Fixed order items pricing info
  commerce-order-web/src/main/resources/META-INF/resources/init.jsp
  commerce-order-web/src/main/resources/META-INF/resources/order/items.jsp
Labels: ci:test - success

#1189 COMMERCE-1640 disable addToCart button only when the option is skuCon…
  commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/render/view.jsp
Labels: ci:test - success

#1185 LPS-98419
  commerce-payment-service/src/main/java/com/liferay/commerce/payment/internal/engine/CommercePaymentEngineImpl.java
  commerce-payment-service/src/main/java/com/liferay/commerce/payment/internal/engine/CommerceSubscriptionEngineImpl.java
  commerce-payment-service/src/main/java/com/liferay/commerce/payment/internal/method/CommercePaymentMethodRegistryImpl.java
  commerce-payment-service/src/main/java/com/liferay/commerce/payment/internal/request/CommercePaymentRequestProviderRegistryImpl.java
  commerce-payment-service/src/main/java/com/liferay/commerce/payment/internal/request/DefaultCommercePaymentRequestProvider.java
  commerce-payment-service/src/main/java/com/liferay/commerce/payment/internal/util/CommercePaymentUtilsImpl.java
Labels: ci:test - success

#1153 COMMERCE-1603 Use the proper class to create service context
  commerce-warehouse-web/src/main/java/com/liferay/commerce/warehouse/web/internal/portlet/action/EditCommerceInventoryWarehouseMVCActionCommand.java
Labels: ci:test - success

#1210 COMMERCE-1630 show facet section only when not empty
  commerce-product-content-search-web/src/main/resources/META-INF/resources/option_facets/view.jsp
  commerce-product-content-search-web/src/main/resources/META-INF/resources/specification_option_facets/view.jsp
Labels: ci:test - success

#1209 COMMERCE-1646 show only facetable specification options
  commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/portlet/CPSpecificationOptionFacetsPortlet.java
Labels: ci:test - success

#1207 LPP-34581 Fixed commerce product definition item selector
  commerce-product-item-selector-web/src/main/java/com/liferay/commerce/product/item/selector/web/internal/display/context/CPDefinitionItemSelectorViewDisplayContext.java
  commerce-product-item-selector-web/src/main/java/com/liferay/commerce/product/item/selector/web/internal/util/CPItemSelectorViewUtil.java
  commerce-product-item-selector-web/src/main/resources/META-INF/resources/definition_item_selector.jsp
Labels: ci:test - success

#1202 COMMERCE-1605 Remove groupId from discount search
  commerce-discount-service/src/main/java/com/liferay/commerce/discount/internal/CommerceDiscountCalculationImpl.java
Labels: ci:test - success

#1204 COMMERCE-1472 Set backURL directly from portletURL
  commerce-channel-web/src/main/java/com/liferay/commerce/channel/web/internal/display/context/CommerceChannelDisplayContext.java
Labels: ci:test - success

#1199 COMMERCE-1616 Add orderId column to shipments list
  commerce-shipment-web/src/main/java/com/liferay/commerce/shipment/web/internal/display/context/CommerceShipmentDisplayContext.java
  commerce-shipment-web/src/main/resources/META-INF/resources/view.jsp
Labels: ci:test - success

#1147 COMMERCE-1612 Make sure that existing users are added to the new site
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CommerceUsersImporter.java
Labels: ci:test - success
