Repository liferay/com-liferay-commerce, pull requests merged in 2019-10, with the labels that each got.

#1475 COMMERCE-1453 Remove SF suppressions fixed by COMMERCE-1594
  source-formatter-suppressions.xml
Labels: ci:test - success

#1474 COMMERCE-1453 Fix JavaModuleServiceProxyFactoryCheck suppression (from Alec)
  commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountLocalServiceImpl.java
  source-formatter-suppressions.xml
Labels: ci:test - success

#1135 COMMERCE-1453 Fix VariableDeclarationAsUsedCheck and remove suppression
  commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/PaymentMethodCommerceCheckoutStep.java
  commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/ShippingMethodCommerceCheckoutStep.java
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/application/context/provider/SortContextProvider.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPAttachmentFileEntryCreator.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPOptionCategoriesImporter.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CommerceInventoryWarehousesImporter.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CommerceOrderImporter.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CommercePriceListsImporter.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/RatingsImporter.java
  commerce-product-asset-categories-navigation-web/src/main/java/com/liferay/commerce/product/asset/categories/navigation/web/internal/display/context/CPAssetCategoriesNavigationDisplayContext.java
  commerce-product-content-category-web/src/main/java/com/liferay/commerce/product/content/category/web/internal/display/context/CPCategoryContentDisplayContext.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/display/context/CPInstanceDisplayContext.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/data/source/BaseCPDataSourceAssetEntryImpl.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/importer/CPFileImporterImpl.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/CPDefinitionSearcher.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/CPInstanceHelperImpl.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/DDMFormValuesHelperImpl.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/data/provider/CPInstanceOptionsValuesDataProvider.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPFriendlyURLEntryLocalServiceImpl.java
  commerce-product-type-virtual-order-content-web/src/main/java/com/liferay/commerce/product/type/virtual/order/content/web/internal/display/context/CommerceVirtualOrderItemContentDisplayContext.java
  commerce-product-type-virtual-order-service/src/main/java/com/liferay/commerce/product/type/virtual/order/internal/messaging/CommerceOrderStatusMessageListener.java
  commerce-product-type-virtual-web/src/main/java/com/liferay/commerce/product/type/virtual/web/internal/display/context/CPDefinitionVirtualSettingDisplayContext.java
  commerce-service/src/main/java/com/liferay/commerce/internal/order/CommerceOrderHttpHelperImpl.java
  commerce-service/src/main/java/com/liferay/commerce/internal/order/DefaultCommerceOrderValidatorImpl.java
  commerce-service/src/main/java/com/liferay/commerce/internal/price/CommerceProductPriceCalculationImpl.java
  commerce-service/src/main/java/com/liferay/commerce/internal/product/content/contributor/AvailabilityCPContentContributor.java
  commerce-service/src/main/java/com/liferay/commerce/internal/product/content/contributor/AvailabilityEstimateCPContentContributor.java
  commerce-service/src/main/java/com/liferay/commerce/internal/product/content/contributor/PriceCPContentContributor.java
  commerce-service/src/main/java/com/liferay/commerce/internal/product/content/contributor/StockQuantityCPContentContributor.java
  commerce-tax-engine-fixed-service/src/main/java/com/liferay/commerce/tax/engine/fixed/internal/engine/ByAddressCommerceTaxEngine.java
  commerce-tax-service/src/main/java/com/liferay/commerce/tax/internal/CommerceTaxCalculationImpl.java
  commerce-theme-minium/commerce-theme-minium-site-initializer/src/main/java/com/liferay/commerce/theme/minium/site/initializer/internal/MiniumSiteInitializer.java
  headless/headless-commerce-core-api/src/main/java/com/liferay/headless/commerce/core/util/LanguageUtils.java
  source-formatter-suppressions.xml
Labels: ci:test - success

#1492 COMMERCE-2238 Remove NPMResolverProvider in cart-taglib and initialize in ServletContextUtil
  commerce-cart-taglib/src/main/java/com/liferay/commerce/cart/taglib/servlet/taglib/AddToCartTag.java
  commerce-cart-taglib/src/main/java/com/liferay/commerce/cart/taglib/servlet/taglib/internal/js/loader/modules/extender/npm/NPMResolverProvider.java
  commerce-cart-taglib/src/main/java/com/liferay/commerce/cart/taglib/servlet/taglib/internal/servlet/ServletContextUtil.java
Labels: ci:test - success

#1491 COMMERCE-2237 Remove NPMResolverProvider from frontend-taglib and initialize in ServletContextUtil
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/internal/js/loader/modules/extender/npm/NPMResolverProvider.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/internal/servlet/ServletContextUtil.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AccountSelectorTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddAccountModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddOrganizationsModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddToCartTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddressModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/CommerceTableTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/CompareCheckboxTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/GalleryTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/MiniCartTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/PriceTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/ProductDetailsModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/QuantitySelectorTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/SearchBarTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/SearchResultsTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/UserInvitationModalTag.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/UserRolesModalTag.java
Labels: ci:test - success

#1494 COMMERCE-2240 Fix SF errors
  commerce-account-service/src/main/java/com/liferay/commerce/account/internal/util/CommerceAccountHelperImpl.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountClayTable.java
  commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/portlet/CommerceCheckoutPortlet.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/internal/servlet/ServletContextUtil.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPDefinitionLinkMVCActionCommand.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/search/CPDefinitionSearcher.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/CPInstanceHelperImpl.java
  commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderLocalServiceImpl.java
  commerce-theme-speedwell/commerce-theme-speedwell-site-initializer/src/main/java/com/liferay/commerce/theme/speedwell/site/initializer/internal/SpeedwellSiteInitializer.java
Labels: ci:test - success

#1496 COMMERCE-1794 Fixed commerce categories navigation
  commerce-product-asset-categories-navigation-web/src/main/java/com/liferay/commerce/product/asset/categories/navigation/web/internal/display/context/CPAssetCategoriesNavigationDisplayContext.java
Labels: ci:test - success

#1509 COMMERCE-1980 Satisfy auto SF
  commerce-notification-service/src/main/java/com/liferay/commerce/notification/service/impl/CommerceNotificationQueueEntryLocalServiceImpl.java
Labels: ci:test - pending

#753 COMMERCE-980 Only add back arrow for accounts if they have more than 1
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountSelector.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountSelector.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/OrdersTable.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/OrdersTable.soy
Labels: ci:test - success

#765 COMMERCE-1239 Make order item checkboxes usable for deleting rows
  commerce-order-web/src/main/resources/META-INF/resources/order/items.jsp
Labels: ci:test - success

#776 COMMERCE-1172 Only get personal accounts if the user isn't deactivated
  commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountLocalServiceImpl.java
Labels: ci:test - success

#1518 COMMERCE-2253 This method should pass userId
  commerce-wish-list-service/src/main/java/com/liferay/commerce/wish/list/service/impl/CommerceWishListServiceImpl.java
Labels: ci:test - success

#1523 Commerce 2259 Fix issue in account groups accounts page caused by pagination
  commerce-account-item-selector-web/src/main/java/com/liferay/commerce/account/item/selector/web/internal/display/context/CommerceAccountItemSelectorViewDisplayContext.java
Labels: ci:test - success

#1522 Commerce 2082 Fix wishlists not working when an account isn't selected
  commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/product_card/ProductCard.es.js
Labels: ci:test - success

#1542 COMMERCE-1992 order web fixed after work on 7.2 compatibility
  commerce-theme-minium/commerce-theme-minium/src/templates/init.ftl
Labels: ci:test - pending

#1549 COMMERCE-2285 Only add top margin if control menu present
  commerce-theme-minium/commerce-theme-minium/src/css/_custom.scss
Labels: ci:test - success

#1547 COMMERCE-2278 Fixed exception message
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPDisplayLayoutMVCActionCommand.java
  commerce-product-definitions-web/src/main/resources/META-INF/resources/display_layout/edit_definition_display_page.jsp
Labels: ci:test - success

#1531 COMMERCE-2260 Add missing AND
  commerce-inventory-service/src/main/resources/META-INF/custom-sql/default.xml
Labels: ci:test - success

#1546 COMMERCE-2310
  commerce-frontend-taglib/bnd.bnd
Labels: ci:test - failure

#1579 COMMERCE-2352 Fix configuration bug
  commerce-notification-service/src/main/java/com/liferay/commerce/notification/internal/configuration/definition/CommerceNotificationQueueEntryServiceConfigurationPidMapping.java
  commerce-notification-service/src/main/java/com/liferay/commerce/notification/internal/constants/CommerceNotificationQueueEntryConstants.java
  commerce-notification-service/src/main/java/com/liferay/commerce/notification/internal/messaging/CheckCommerceNotificationQueueEntryMessageListener.java
Labels: ci:test - success

#1605 Fix some imports for 7.2 compat
  commerce-account-web/bnd.bnd
  commerce-admin-web/bnd.bnd
  commerce-frontend-taglib/bnd.bnd
  commerce-notification-web/bnd.bnd
  commerce-order-content-web/bnd.bnd
  commerce-order-web/bnd.bnd
  commerce-price-list-web/bnd.bnd
  commerce-product-definitions-web/bnd.bnd
  commerce-product-measurement-unit-web/bnd.bnd
  commerce-product-options-web/bnd.bnd
  commerce-subscription-web/bnd.bnd
Labels: ci:test - failure

#1609 COMMERCE-1551 remove module merged by mistake
  commerce-inventory-test-util/build.gradle
Labels: ci:test - failure
