Repository liferay/com-liferay-commerce, pull requests merged in 2019-03, with the labels that each got.

#610 COMMERCE-686 CSS refactor
  commerce-frontend-taglib/src/main/resources/META-INF/liferay-commerce-ui.tld
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountSelector.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountsTable.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/AccountsTableItem.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/account_selector/OrdersTable.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_tick_item/AddToTickItem.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/clay_table/CommerceTable.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/CartProduct.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/MiniCart.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/product_details_modal/ProductDetailsModal.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/quantity_selector/QuantitySelector.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/search_bar/SearchBar.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/search_bar/SearchBar.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/search_results/SearchResults.soy
Labels: ci:test - failure

#671 COMMERCE-1164 User should have site membership when added to account
  commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountUserRelLocalServiceImpl.java
Labels: ci:test - success

#670 COMMERCE-1117 Clean extra cache
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPRuleLocalServiceImpl.java
Labels: ci:test - success

#665 COMMERCE-1160 We shouldn't always pass true for compare checkbox
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/CompareCheckboxTag.java
Labels: ci:test - success

#649 COMMERCE-1142 Fix language key
  commerce-service/src/main/java/com/liferay/commerce/internal/order/AvailabilityCommerceOrderValidatorImpl.java
Labels: ci:test - success

#663 Fix Removal of AccountRel on Price Lists
  commerce-price-list-web/src/main/resources/META-INF/resources/price_list/details.jsp
Labels: ci:test - success

#667 COMMERCE-1113 Implement rowChecker to disable checkbox for System User Segments
  commerce-user-segment-web/src/main/java/com/liferay/commerce/user/segment/web/internal/display/context/CommerceUserSegmentDisplayContext.java
  commerce-user-segment-web/src/main/java/com/liferay/commerce/user/segment/web/internal/search/CommerceUserSegmentEntryChecker.java
  commerce-user-segment-web/src/main/resources/META-INF/resources/view.jsp
Labels: ci:test - success

#661 COMMERCE-1153 Replace DLUtil with CommerceMediaResolver
  commerce-product-asset-categories-navigation-web/build.gradle
  commerce-product-asset-categories-navigation-web/src/main/java/com/liferay/commerce/product/asset/categories/navigation/web/internal/display/context/CPAssetCategoriesNavigationDisplayContext.java
  commerce-product-asset-categories-navigation-web/src/main/java/com/liferay/commerce/product/asset/categories/navigation/web/internal/portlet/CPAssetCategoriesNavigationPortlet.java
  commerce-product-asset-categories-navigation-web/src/main/java/com/liferay/commerce/product/asset/categories/navigation/web/internal/portlet/action/CPAssetCategoriesNavigationConfigurationAction.java
  commerce-product-asset-categories-web/build.gradle
  commerce-product-asset-categories-web/src/main/resources/META-INF/resources/images.jsp
  commerce-product-asset-categories-web/src/main/resources/META-INF/resources/init.jsp
  commerce-product-content-category-web/build.gradle
  commerce-product-content-category-web/src/main/java/com/liferay/commerce/product/content/category/web/internal/display/context/CPCategoryContentDisplayContext.java
  commerce-product-content-category-web/src/main/java/com/liferay/commerce/product/content/category/web/internal/portlet/CPCategoryContentPortlet.java
  commerce-product-content-category-web/src/main/java/com/liferay/commerce/product/content/category/web/internal/portlet/action/CPCategoryContentConfigurationAction.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/util/CPContentHelperImpl.java
  commerce-product-definitions-web/build.gradle
  commerce-product-definitions-web/src/main/resources/META-INF/resources/attachment_file_entries.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/init.jsp
Labels: ci:test - success

#680 Commerce 1153 Source formatting
  commerce-product-asset-categories-navigation-web/build.gradle
  commerce-product-asset-categories-web/build.gradle
  commerce-product-content-category-web/build.gradle
  commerce-product-definitions-web/build.gradle
Labels: ci:test - failure

#681 COMMERCE-872 Fix JS dependencies
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rels.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/toolbar.jsp
  commerce-product-options-web/src/main/resources/META-INF/resources/view.jsp
  commerce-theme-minium/commerce-theme-minium-impl/src/main/java/com/liferay/commerce/theme/minium/internal/product/renderer/list/entry/MiniumCPContentListEntryRenderer.java
Labels: ci:test - pending

#683 COMMERCE-1175 replace portal.sendError with log.error due to the poss…
  commerce-payment-method-paypal/src/main/java/com/liferay/commerce/payment/method/paypal/internal/servlet/CommercePaymentMethodPayPalServlet.java
Labels: ci:test - success

#682 COMMERCE-1174 Fix attachment table and edit page
  commerce-product-definitions-web/src/main/resources/META-INF/resources/attachment_file_entries.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/attachment_file_entry_action.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/attachment_file_entry_columns.jspf
Labels: ci:test - success

#675 COMMERCE-1166 Use redirect passed in form
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPDefinitionLinkMVCActionCommand.java
Labels: ci:test - success

#697 COMMERCE-0 ignoring test for now
  commerce-payment-test/build.gradle
  commerce-payment-test/src/testIntegration/java/com/liferay/commerce/payment/engine/test/CommercePaymentEngineTest.java
Labels: ci:test - success

#707 EMP-18 Fail if JVM opts aren't reset to prevent insufficient memory
  build_bundle.sh
Labels: ci:test - failure

#684 COMMERCE-686 icon file refactored
  commerce-theme-minium/commerce-theme-minium/src/images/commerce-icons.svg
Labels: ci:test - success

#693 COMMERCE-1173 Site Members should have VIEW perm for categories
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/AssetCategoriesImporter.java
Labels: ci:test - failure

#698 COMMERCE-1184 Only update the payment key if it doesn't match the existing one
  commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/CommerceCheckoutStepHelper.java
Labels: ci:test - failure

#691 COMMERCE-1178 Render command should be plural
  commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/asset/CommerceOrderAssetRenderer.java
  commerce-order-web/src/main/resources/META-INF/resources/order_action.jsp
Labels: ci:test - failure

#692 COMMERCE-1165 | 7.1.x-next
  commerce-cart-taglib/build.gradle
  commerce-frontend-impl/build.gradle
  commerce-openapi-admin/build.gradle
  commerce-openapi-core-api/build.gradle
  commerce-openapi-core-impl/build.gradle
  commerce-payment-method-mercanet/build.gradle
  headless/headless-commerce/headless-commerce-admin-site-setting/build.gradle
Labels: ci:test - failure

#687 COMMERCE-992 Add backUrl handling after editing account user
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/portlet/action/EditCommerceAccountUserMVCActionCommand.java
Labels: ci:test - failure

#695 COMMERCE-1176 Use the account's groupId instead of sites to delete workflow
  commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderLocalServiceImpl.java
Labels: ci:test - failure

#699 COMMERCE-998 B2C-B2B Site Admin should see both types of accounts
  commerce-account-service/src/main/java/com/liferay/commerce/account/service/impl/CommerceAccountServiceImpl.java
Labels: ci:test - failure

#694 COMMERCE-991 User accountId from member model
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountUserClayTable.java
Labels: ci:test - failure

#688 COMMERCE-0 source format
  commerce-payment-method-mercanet/src/main/java/com/liferay/commerce/payment/method/mercanet/internal/servlet/MercanetServlet.java
Labels: ci:test - failure

#718 COMMERCE-0 SF
  commerce-account-web/build.gradle
  commerce-frontend-taglib/bnd.bnd
  commerce-frontend-taglib/src/main/resources/META-INF/liferay-commerce-ui.tld
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCartButton.es.js
  commerce-openapi-admin/build.gradle
  commerce-openapi-core-impl/build.gradle
  commerce-order-content-web/build.gradle
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/CPInstanceHelperImpl.java
  commerce-test/src/testIntegration/java/com/liferay/commerce/discount/test/CommerceDiscountTest.java
  commerce-theme-minium/commerce-theme-minium-impl/build.gradle
  commerce-user-segment-test/src/testIntegration/java/com/liferay/commerce/user/segment/internal/search/test/CommerceUserSegmentEntryIndexerTest.java
Labels: ci:test - pending

#723 COMMERCE-1212 Remove XSS vulnerabilities
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/account/model/Account.java
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/account/model/AccountUser.java
  commerce-initializer-breccia/src/main/resources/META-INF/resources/render/init.jsp
  commerce-initializer-breccia/src/main/resources/META-INF/resources/render/list_entry/search_result.jsp
  commerce-initializer-breccia/src/main/resources/META-INF/resources/render/view.jsp
  commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/BRECCIA_COMMERCE_CART_CONTENT.ftl
  commerce-order-web/src/main/resources/META-INF/resources/order_item/detail.jsp
  commerce-price-list-web/src/main/resources/META-INF/resources/instance_price_lists.jsp
  commerce-product-content-web/src/main/resources/META-INF/resources/product_publisher/configuration/product_entries.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/instance_columns.jspf
  commerce-product-type-grouped-web/src/main/resources/META-INF/resources/render/view.jsp
  commerce-product-type-grouped-web/src/main/resources/com/liferay/commerce/product/type/grouped/web/internal/template/dependencies/portlet_display_template_basic.ftl
  commerce-product-type-simple/src/main/resources/META-INF/resources/init.jsp
  commerce-product-type-simple/src/main/resources/META-INF/resources/render/list_entry/compare_product_mini.jsp
  commerce-product-type-simple/src/main/resources/META-INF/resources/render/list_entry/default.jsp
  commerce-product-type-simple/src/main/resources/META-INF/resources/render/view.jsp
  commerce-product-type-simple/src/main/resources/com/liferay/commerce/product/type/simple/internal/template/dependencies/portlet_display_template_basic.ftl
  commerce-product-type-virtual-web/src/main/resources/META-INF/resources/render/view.jsp
  commerce-product-type-virtual-web/src/main/resources/com/liferay/commerce/product/type/virtual/web/internal/template/dependencies/portlet_display_template_basic.ftl
  commerce-shipment-content-web/src/main/resources/META-INF/resources/view_shipment_items.jsp
  commerce-shipment-web/src/main/resources/META-INF/resources/shipment/items.jsp
  commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/init.jsp
  commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/render/view.jsp
Labels: ci:test - failure

#730 COMMERCE-0 We still need these dependencies for compile-time
  commerce-payment-test/build.gradle
Labels: ci:test - success

#743 COMMERCE-1218 Add validation
  commerce-taglib/src/main/java/com/liferay/commerce/taglib/servlet/taglib/TierPriceTag.java
Labels: ci:test - success

#736 LPP-33432 changed how transaction reference is generated
  commerce-payment-method-mercanet/src/main/java/com/liferay/commerce/payment/method/mercanet/internal/MercanetCommercePaymentMethod.java
  commerce-payment-method-mercanet/src/main/java/com/liferay/commerce/payment/method/mercanet/internal/servlet/MercanetServlet.java
Labels: ci:test - success

#738 COMMERCE-1223 fix 'Use Shipping Address as Billing Address' checkbox formatting
  commerce-checkout-web/src/main/resources/META-INF/resources/checkout_step/address.jsp
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/overrides/_checkout-page.scss
Labels: ci:test - success

#742 COMMERCE-1220 Inventory quantity must be numeric
  commerce-service/src/main/resources/META-INF/portlet-model-hints.xml
Labels: ci:test - success

#739 COMMERCE-550 Make Open the default Orders tab
  commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/display/context/CommerceOrderListDisplayContext.java
Labels: ci:test - success

#744 COMMERCE-986 Set backURL so the cancel button can use it
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/account/CommerceAccountResource.java
  commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/frontend/util/CommerceOrderClayTableUtil.java
Labels: ci:test - success
