Repository liferay/com-liferay-commerce, pull requests merged in 2019-09, with the labels that each got.

#1319 COMMERCE-1729 Add error handling for OrderValidatorExceptions on the order details page
  commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/portlet/action/EditCommerceOrderMVCActionCommand.java
  commerce-order-content-web/src/main/resources/META-INF/resources/placed_orders/view_order_details.jsp
Labels: ci:test - success

#1317 COMMERCE-1716 Make sure channelIds are unique
  commerce-discount-web/src/main/resources/META-INF/resources/discount/detail.jsp
  commerce-discount-web/src/main/resources/META-INF/resources/discount/detail_channels.jspf
Labels: ci:test - success

#1315 COMMERCE-1726 retrieve guest cart after login from cookie
  commerce-service/src/main/java/com/liferay/commerce/internal/order/CommerceOrderHttpHelperImpl.java
Labels: ci:test - success

#1311 COMMERCE-1790 Fixed order dto converter
  headless/headless-commerce/headless-commerce-admin-order-impl/src/main/java/com/liferay/headless/commerce/admin/order/internal/dto/v1_0/converter/OrderDTOConverter.java
Labels: ci:test - success

#1300 COMMERCE-1670 Only allow address creation if the first and second mod…
  commerce-frontend-taglib/src/main/resources/META-INF/resources/address_modal/AddressModal.es.js
Labels: ci:test - success

#1294 EMP-40 Fix CPOption Facet to allow localization and to use name field…
  commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/portlet/CPOptionFacetsPortlet.java
  commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/util/CPOptionFacetsUtil.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/search/CPDefinitionIndexer.java
Labels: ci:test - success

#1327 COMMERCE-1811 remove stock check of the current order quantity since …
  commerce-service/src/main/java/com/liferay/commerce/internal/order/AvailabilityCommerceOrderValidatorImpl.java
Labels: ci:test - success

#1326 COMMERCE-1740 Take care of reservedQuantity when calculating stock qu…
  commerce-inventory-service/src/main/resources/META-INF/custom-sql/default.xml
Labels: ci:test - success

#1321 COMMERCE-1808 align to PayPal APIs when validating recurring payment …
  commerce-payment-method-paypal/src/main/java/com/liferay/commerce/payment/method/paypal/internal/PayPalCommercePaymentMethod.java
  commerce-service/src/main/java/com/liferay/commerce/internal/subscription/CommerceSubscriptionEntryHelperImpl.java
Labels: ci:test - success

#1318 COMMERCE-1723 Extract Text from full description to avoid html tags
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/search/CommerceSearchResource.java
Labels: ci:test - success

#1309 COMMERCE-1706 cancel button deleted on "product option value" modal
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rel/CPDefinitionOptionValueDetail.es.js
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rel/CPDefinitionOptionValueDetail.soy
Labels: ci:test - success

#1368 Revert "RELEASE-1813 Satisfy auto SF by refreshing js dep versions"
  commerce-theme-minium/commerce-theme-minium-impl/package.json
Labels: ci:test - success

#1369 COMMERCE-1911 Corrected type_ field name
  commerce-service/src/main/java/com/liferay/commerce/internal/upgrade/v4_1_0/CommerceAddressUpgradeProcess.java
Labels: ci:test - success

#1361 COMMERCE-1842 Make sure that shipment pull the correct order statuses and workflow approved
  commerce-api/src/main/java/com/liferay/commerce/constants/CommerceShipmentConstants.java
  commerce-service/src/main/java/com/liferay/commerce/internal/search/CommerceOrderIndexer.java
  commerce-shipment-web/src/main/java/com/liferay/commerce/shipment/web/internal/display/context/CommerceShipmentDisplayContext.java
Labels: ci:test - success

#1359 COMMERCE-1786 Improve null/empty handling and simplify logic
  commerce-account-service/src/main/java/com/liferay/commerce/account/service/persistence/impl/CommerceAccountGroupFinderImpl.java
  commerce-notification-service/src/main/java/com/liferay/commerce/notification/internal/util/CommerceNotificationHelperImpl.java
Labels: ci:test - success

#1372 COMMERCE-1823 Removed unecessary search bar
  commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_definition_account_groups.jsp
Labels: ci:test - success

#1371 COMMERCE-1822 Fixed product's account groups pagination
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/display/context/CPDefinitionAccountGroupDisplayContext.java
Labels: ci:test - success

#1349 COMMERCE-1840 In address modal get countries by channelId
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/address/AddressResource.java
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddressModalTag.java
  commerce-frontend-taglib/src/main/resources/META-INF/resources/address_modal/AddressModal.es.js
Labels: ci:test - success

#1384 COMMERCE-1621 Set p_auth for all ajax requests
  commerce-cart-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCart.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_account_modal/AddAccountModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_organizations_modal/AddOrganizationsModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/add_to_cart/AddToCartButton.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/address_modal/AddressModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/MiniCart.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/search_results/SearchResults.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_invitation_modal/UserInvitationModal.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/user_utils/UserInvitation.es.js
  commerce-product-definitions-web/src/main/resources/META-INF/resources/DefinitionToolbarFilter.es.js
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rel/CPDefinitionOptionDetail.es.js
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rel/CPDefinitionOptionValueDetail.es.js
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rel/CPDefinitionOptionValuesEditor.es.js
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rel/CPDefinitionOptionsEditor.es.js
  commerce-product-options-web/src/main/resources/META-INF/resources/CPOptionDetail.es.js
  commerce-product-options-web/src/main/resources/META-INF/resources/CPOptionValueDetail.es.js
  commerce-product-options-web/src/main/resources/META-INF/resources/CPOptionValuesEditor.es.js
  commerce-product-options-web/src/main/resources/META-INF/resources/CPOptionsEditor.es.js
  commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/product_card/ProductCard.es.js
  commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/products_compare/ProductsCompare.es.js
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/account-selector/src/AccountSelector.js
  commerce-theme-minium/commerce-theme-minium/static-version/public/soy-components/user-invitation/src/UserInvitation.js
Labels: ci:test - success

#1380 COMMERCE-1819 back button point to the account group page
  commerce-account-group-admin-web/src/main/java/com/liferay/commerce/account/group/admin/web/internal/portlet/action/EditCommerceAccountGroupMVCActionCommand.java
Labels: ci:test - success

#1389 COMMERCE-1961 Reset form validation if they're changing to an existing address
  commerce-checkout-web/src/main/resources/META-INF/resources/checkout_step/address.jsp
Labels: ci:test - success

#1387 COMMERCE-1821 fixed translation issue
  commerce-account-item-selector-web/src/main/resources/META-INF/resources/account_group_item_selector.jsp
Labels: ci:test - success

#1386 COMMERCE-1960 Make sure we're using the localized index fildname
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/CPDefinitionsFacetsMVCResourceCommand.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java
Labels: ci:test - success

#1394 COMMERCE-1621 Fix P_Auth bug
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/AddressModalTag.java
  commerce-frontend-taglib/src/main/resources/META-INF/resources/address_modal/AddressModal.es.js
Labels: ci:test - pending

#1391 (SF fixes) Commerce 1855 - Demo Initializer
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/display/context/CommerceAccountAdminDisplayContext.java
  commerce-account-admin-web/src/main/resources/META-INF/resources/account/detail.jsp
  commerce-account-admin-web/src/main/resources/META-INF/resources/edit_address.jsp
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CommercePriceListsImporter.java
Labels: ci:test - success

#1376 (SF Fix) COMMERCE-1842 Re-order constants alphabetically
  commerce-api/src/main/java/com/liferay/commerce/constants/CommerceShipmentConstants.java
Labels: ci:test - success

#1375 (SF Fix) COMMERCE-1786 Switch return new ArrayList to Collections.emptyList
  commerce-account-service/src/main/java/com/liferay/commerce/account/service/persistence/impl/CommerceAccountGroupFinderImpl.java
Labels: ci:test - success

#1289 COMMERCE-686 fix css search overlay
  commerce-theme-minium/commerce-theme-minium/src/css/_custom.scss
Labels: ci:test - success

#1228 COMMERCE-1684 Add functionality to assign users' account roles in con…
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/display/context/CommerceAccountUserRelAdminDisplayContext.java
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/portlet/action/EditCommerceAccountUserRelMVCActionCommand.java
  commerce-account-admin-web/src/main/resources/META-INF/resources/account/users.jsp
  commerce-account-admin-web/src/main/resources/META-INF/resources/user_action.jsp
Labels: ci:test - success

#1314 COMMERCE-1701 Remove copyright from Minium as it's unused
  commerce-theme-minium/commerce-theme-minium/src/WEB-INF/liferay-look-and-feel.xml
  commerce-theme-minium/commerce-theme-minium/src/templates/init_custom.ftl
Labels: ci:test - success

#1078 COMMERCE-1550 restore commerce currency integration tests
  commerce-currency-test/src/testIntegration/java/com/liferay/commerce/currency/util/test/CommercePriceFormatterTest.java
Labels: ci:test - success

#1077 COMMERCE-1530 restore commerce account integration tests
  commerce-account-test/src/testIntegration/java/com/liferay/commerce/account/service/test/CommerceAccountLocalServiceTest.java
Labels: ci:test - success

#1233 Commerce 997 & 1216 Add name fields to user edit page and fix permissions allowing Account Admin update permissions
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/display/context/CommerceAccountDisplayContext.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/portlet/action/EditCommerceAccountUserMVCActionCommand.java
  commerce-account-web/src/main/resources/META-INF/resources/edit_user.jsp
  commerce-account-web/src/main/resources/META-INF/resources/init.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view.jsp
  commerce-account-web/src/main/resources/META-INF/resources/view_user.jsp
Labels: ci:test - success

#1079 COMMERCE-1553 fix commerce price list tests
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/internal/search/test/CommercePriceListIndexerTest.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/service/test/CommercePriceEntryLocalServiceTest.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/service/test/CommercePriceListLocalServiceTest.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/service/test/CommerceTierPriceEntryLocalServiceTest.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/test/util/CommercePriceEntryTestUtil.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/test/util/CommercePriceListTestUtil.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/test/util/CommerceTierPriceEntryTestUtil.java
Labels: ci:test - success

#1417 COMMERCE-1977 if no channel is found return empty list
  commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceShipmentServiceImpl.java
Labels: ci:test - failure

#1415 COMMERCE-2013 Fixed dto converter contexts
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/OptionCategoryResourceImpl.java
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/OptionResourceImpl.java
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductOptionResourceImpl.java
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/RelatedProductResourceImpl.java
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/SpecificationResourceImpl.java
  headless/headless-commerce/headless-commerce-admin-order-impl/src/main/java/com/liferay/headless/commerce/admin/order/internal/resource/v1_0/OrderItemResourceImpl.java
  headless/headless-commerce/headless-commerce-admin-order-impl/src/main/java/com/liferay/headless/commerce/admin/order/internal/resource/v1_0/OrderNoteResourceImpl.java
Labels: ci:test - failure

#1413 COMMERCE-1962 Change currency name for not duplicating it
  commerce-product-test/src/testFunctional/macros/CommerceConfiguration.macro
Labels: ci:test - failure

#1419 COMMERCE-1684 Source Formatting
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/display/context/CommerceAccountUserRelAdminDisplayContext.java
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/portlet/action/EditCommerceAccountUserRelMVCActionCommand.java
  commerce-account-admin-web/src/main/resources/META-INF/resources/user_action.jsp
Labels: ci:test - failure

#1379 COMMERCE-1738 added check on array emptiness
  commerce-payment-web/src/main/java/com/liferay/commerce/payment/web/internal/display/context/CommercePaymentMethodGroupRelsDisplayContext.java
Labels: ci:test - success

#1433 COMMERCE-1553 fix commerceCurrency for price list integration tests
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/service/test/CommercePriceEntryLocalServiceTest.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/service/test/CommercePriceListLocalServiceTest.java
  commerce-price-list-test/src/testIntegration/java/com/liferay/commerce/price/list/service/test/CommerceTierPriceEntryLocalServiceTest.java
Labels: ci:test - failure

#1450 COMMERCE-1951 added skus to products
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/converter/ProductDTOConverter.java
Labels: ci:test - success

#1448 COMMERCE-1687 Add upgrade process for updating CPAttachment groupIds
  commerce-product-service/bnd.bnd
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/upgrade/CommerceProductUpgradeStepRegistrator.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/upgrade/v1_8_0/CPAttachmentFileEntryUpgradeProcess.java
Labels: ci:test - success

#1429 Commerce 1698 Source Formatting
  commerce-account-service/src/main/java/com/liferay/commerce/account/internal/util/CommerceAccountHelperImpl.java
  commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderServiceImpl.java
Labels: ci:test - success

#1428 EMP-82 Add new optional to make sure paginationDelta is pulled from configuration
  commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/portlet/CPSearchResultsPortlet.java
Labels: ci:test - success

#1443 COMMERCE-1744 Fixed product instances item selector sort
  commerce-product-item-selector-web/src/main/java/com/liferay/commerce/product/item/selector/web/internal/util/CPItemSelectorViewUtil.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/search/CPInstanceIndexer.java
Labels: ci:test - failure

#1442 COMMERCE-1700 Fixed account admin edit screen nvigation visibility
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/servlet/taglib/ui/CommerceAccountAddressScreenNavigationEntry.java
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/servlet/taglib/ui/CommerceAccountOrganizationRelScreenNavigationEntry.java
  commerce-account-admin-web/src/main/java/com/liferay/commerce/account/admin/web/internal/servlet/taglib/ui/CommerceAccountUserRelScreenNavigationEntry.java
Labels: ci:test - failure

#1444 COMMERCE-1755 Fixed edit account user back url
  commerce-account-web/src/main/resources/META-INF/resources/view_user.jsp
Labels: ci:test - failure

#1441 COMMERCE-1754 Fixed commerce account address clay table actions
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountAddressClayTable.java
Labels: ci:test - failure

#1438 COMMERCE-1768 fixed cell width on shipments table
  commerce-shipment-web/src/main/resources/META-INF/resources/select_shipment_items.jsp
Labels: ci:test - failure

#1430 COMMERCE-2019 Default initialized addresses to be the default billing and shipping
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CommerceAccountsImporter.java
Labels: ci:test - failure

#1434 EMP-84 fixed input text ui on old cart taglib
  commerce-taglib/src/main/resources/META-INF/resources/quantity_input/page.jsp
Labels: ci:test - failure

#1345 COMMERCE-1581 fixed colums witdh on compare table with custom style
  commerce-product-type-simple/src/main/resources/META-INF/resources/render/list_entry/compare_product.jsp
Labels: ci:test - failure

#1283 COMMERCE-1258 minium dropdown zindex
  commerce-theme-minium/commerce-theme-minium/src/css/_custom.scss
Labels: ci:test - failure

#1458 EMP-93 fix return code
  headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseResourceImpl.java
Labels: ci:test:relevant - success

#1287 COMMERCE-1694 Checkout step titles max-width is now increased
  commerce-theme-minium/commerce-theme-minium/src/css/minium/overrides/_checkout-page.scss
Labels: ci:test - success

#1459 COMMERCE-1951 changes according to PRs
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/converter/ProductDTOConverter.java
Labels: ci:test - success

#1455 COMMERCE-1953 Only bump versions as much as necessary
  commerce-product-content-web/build.gradle
  commerce-product-definitions-web/build.gradle
Labels: ci:test - success

#1402 COMMECE-1430 Minicart is aware of order workflow now
  commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/MiniCartTag.java
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/MiniCart.es.js
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/MiniCart.soy
  commerce-frontend-taglib/src/main/resources/META-INF/resources/mini_cart/Summary.soy
Labels: ci:test - success
