Repository liferay/com-liferay-commerce, pull requests merged in 2019-12, with the labels that each got.

#1722 COMMERCE-2479 commerce-machine-learning-impl 7.2 compatibility
  commerce-machine-learning-impl/bnd.bnd
Labels: ci:test - failure

#1720 COMMERCE-2496 Fix Speedwell JS due to changed Liferay FE API
  commerce-theme-speedwell/commerce-theme-speedwell-site-initializer/src/main/resources/com/liferay/commerce/theme/speedwell/site/initializer/internal/dependencies/journal_articles/SPEEDWELL_BUMPER_SLIDER.ftl
  commerce-theme-speedwell/commerce-theme-speedwell-site-initializer/src/main/resources/com/liferay/commerce/theme/speedwell/site/initializer/internal/dependencies/journal_articles/SPEEDWELL_HIGHLIGHT_SLIDER.ftl
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/accessibility.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/categoryMenu.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/context.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/init.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/mobile.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/scrollHandler.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/searchBar.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/features/topbar.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/main.js
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/standalone/SpeedwellSlider.js
Labels: ci:test - failure

#1543 COMMERCE-2282
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/CPVersionContributorRegistryImpl.java
Labels: ci:test - failure

#1730 COMMERCE-2501 Improved Speedwell JS init to prevent SPA-caused freeze-up
  commerce-theme-speedwell/commerce-theme-speedwell-site-initializer/src/main/resources/com/liferay/commerce/theme/speedwell/site/initializer/internal/dependencies/journal_articles/SPEEDWELL_BUMPER_SLIDER.ftl
  commerce-theme-speedwell/commerce-theme-speedwell-site-initializer/src/main/resources/com/liferay/commerce/theme/speedwell/site/initializer/internal/dependencies/journal_articles/SPEEDWELL_HIGHLIGHT_SLIDER.ftl
  commerce-theme-speedwell/commerce-theme-speedwell/src/js/main.js
Labels: ci:test - failure

#1573 COMMERCE-2250 Use custom validator for checkout address country field
  commerce-checkout-web/src/main/resources/META-INF/resources/checkout_step/address.jsp
Labels: ci:test - success

#1746 COMMERCE-2290 Fix groupId for setting current account
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/portlet/action/EditCommerceAccountMVCActionCommand.java
Labels: ci:test - failure

#1732 COMMERCE-1687 Add upgrade process to fix CPAttachmentFileEntry's groupId
  commerce-product-service/bnd.bnd
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/upgrade/CommerceProductUpgradeStepRegistrator.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/upgrade/v1_11_0/CPAttachmentFileEntryGroupUpgradeProcess.java
Labels: ci:test - failure

#1744 COMMERCE-1547 commerce-machine-learning-impl Fix User recommendation …
  commerce-machine-learning-impl/src/main/java/com/liferay/commerce/machine/learning/internal/recommendation/data/source/UserCommerceMLRecommendationCPDataSourceImpl.java
Labels: ci:test - failure

#1755 COMMERCE-2519
  headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/resource/v1_0/ProductResourceImpl.java
Labels: ci:test - pending

#1743 COMMERCE-2478 commerce-account-web Memebers role pagination not working
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/AccountFilterFactoryImpl.java
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountUserRolesClayTable.java
Labels: ci:test - failure

#1740 COMMERCE-2356 commerce-lang Missing language keys in the Control Panel
  commerce-lang/src/main/resources/content/Language.properties
  commerce-lang/src/main/resources/content/Language_ar.properties
  commerce-lang/src/main/resources/content/Language_bg.properties
  commerce-lang/src/main/resources/content/Language_ca.properties
  commerce-lang/src/main/resources/content/Language_cs.properties
  commerce-lang/src/main/resources/content/Language_da.properties
  commerce-lang/src/main/resources/content/Language_de.properties
  commerce-lang/src/main/resources/content/Language_el.properties
  commerce-lang/src/main/resources/content/Language_en.properties
  commerce-lang/src/main/resources/content/Language_es.properties
  commerce-lang/src/main/resources/content/Language_et.properties
  commerce-lang/src/main/resources/content/Language_eu.properties
  commerce-lang/src/main/resources/content/Language_fa.properties
  commerce-lang/src/main/resources/content/Language_fi.properties
  commerce-lang/src/main/resources/content/Language_fr.properties
  commerce-lang/src/main/resources/content/Language_gl.properties
  commerce-lang/src/main/resources/content/Language_hi_IN.properties
  commerce-lang/src/main/resources/content/Language_hr.properties
  commerce-lang/src/main/resources/content/Language_hu.properties
  commerce-lang/src/main/resources/content/Language_in.properties
  commerce-lang/src/main/resources/content/Language_it.properties
  commerce-lang/src/main/resources/content/Language_iw.properties
  commerce-lang/src/main/resources/content/Language_ja.properties
  commerce-lang/src/main/resources/content/Language_kk.properties
  commerce-lang/src/main/resources/content/Language_ko.properties
  commerce-lang/src/main/resources/content/Language_lo.properties
  commerce-lang/src/main/resources/content/Language_lt.properties
  commerce-lang/src/main/resources/content/Language_nb.properties
  commerce-lang/src/main/resources/content/Language_nl.properties
  commerce-lang/src/main/resources/content/Language_nl_BE.properties
  commerce-lang/src/main/resources/content/Language_pl.properties
  commerce-lang/src/main/resources/content/Language_pt_BR.properties
  commerce-lang/src/main/resources/content/Language_pt_PT.properties
  commerce-lang/src/main/resources/content/Language_ro.properties
  commerce-lang/src/main/resources/content/Language_ru.properties
  commerce-lang/src/main/resources/content/Language_sk.properties
  commerce-lang/src/main/resources/content/Language_sl.properties
  commerce-lang/src/main/resources/content/Language_sr_RS.properties
  commerce-lang/src/main/resources/content/Language_sr_RS_latin.properties
  commerce-lang/src/main/resources/content/Language_sv.properties
  commerce-lang/src/main/resources/content/Language_ta_IN.properties
  commerce-lang/src/main/resources/content/Language_th.properties
  commerce-lang/src/main/resources/content/Language_tr.properties
  commerce-lang/src/main/resources/content/Language_uk.properties
  commerce-lang/src/main/resources/content/Language_vi.properties
  commerce-lang/src/main/resources/content/Language_zh_CN.properties
  commerce-lang/src/main/resources/content/Language_zh_TW.properties
Labels: ci:test - failure

#1737 LRCI-801 Deploy Commerce like other modules
  commerce-product-test/src/testFunctional/tests/CommerceAdmin.testcase
  commerce-product-test/src/testFunctional/tests/CommerceFrontStore.testcase
Labels: ci:test - failure

#1710 COMMERCE-2488 Added capability to pass subscription ifno
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java
Labels: ci:test - failure

#1765 COMMERCE-2488 Fix initialization issues
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java
Labels: ci:test - failure

#1762 COMMERCE-2522
  headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/jaxrs/exception/mapper/NoSuchInventoryWarehouseExceptionMapper.java
  headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/jaxrs/exception/mapper/NoSuchInventoryWarehouseItemExceptionMapper.java
  headless/headless-commerce/headless-commerce-admin-inventory-impl/src/main/java/com/liferay/headless/commerce/admin/inventory/internal/resource/v1_0/WarehouseItemResourceImpl.java
Labels: ci:test - failure

#1758 COMMERCE-2509 commerce-product-service Do not unpack option values
  commerce-product-service/src/main/java/com/liferay/commerce/product/internal/util/DDMFormValuesHelperImpl.java
Labels: ci:test - failure

#1756 COMMERCE-1699 Channel filters shown only if enabled
  commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_definition_channels.jsp
Labels: ci:test - pending

#1769 COMMERCE-2518 Minium login fixed
  commerce-theme-minium/commerce-theme-minium/src/css/_login.scss
Labels: ci:test - pending

#1772 COMMERCE-2442 Minium styled pagination
  commerce-theme-minium/commerce-theme-minium/src/css/minium/minium.scss
  commerce-theme-minium/commerce-theme-minium/src/css/minium/overrides/_pagination_bar.scss
Labels: ci:test - pending

#1773 COMEMRCE-2527 Fixed Minicart Price styles
  commerce-theme-minium/commerce-theme-minium/src/css/minium/components/mini_cart_item.scss
Labels: ci:test - failure

#1779 COMMERCE-2512 Fix category friendlyUrl cancel button
  commerce-product-asset-categories-web/src/main/resources/META-INF/resources/friendly_url.jsp
Labels: ci:test - failure

#1784 COMMERCE-2525 Update bnd schema version to match latest upgrade
  commerce-product-service/bnd.bnd
Labels: ci:test - failure

#1778 COMMERCE-2520 Fixed Minicart overlapping with LFR sidebars
  commerce-theme-minium/commerce-theme-minium/src/css/minium/_variables.scss
  commerce-theme-minium/commerce-theme-minium/src/css/minium/components/mini_cart.scss
Labels: ci:test - failure

#1774 COMMERCE-2528 Minium liferay topbar variable definition corrected
  commerce-theme-minium/commerce-theme-minium/src/css/minium/_variables.scss
  commerce-theme-minium/commerce-theme-minium/src/css/minium/overrides/_base.scss
  commerce-theme-speedwell/commerce-theme-speedwell/src/css/_overrides.scss
  commerce-theme-speedwell/commerce-theme-speedwell/src/css/_variables.scss
Labels: ci:test - failure

#1790 COMMERCE-1660 Fixed prices visuals
  commerce-frontend-taglib/src/main/resources/META-INF/resources/price/Price.soy
  commerce-theme-minium/commerce-theme-minium/src/css/minium/components/minium_card.scss
  commerce-theme-minium/commerce-theme-minium/src/css/minium/components/price.scss
  commerce-theme-speedwell/commerce-theme-speedwell/src/css/components/_minium_card.scss
  commerce-theme-speedwell/commerce-theme-speedwell/src/css/components/_pagination_bar.scss
  commerce-theme-speedwell/commerce-theme-speedwell/src/css/components/_price.scss
Labels: ci:test - pending

#1795 COMMERCE-2536 Delete temp files
  commerce-data-integration-talend/src/main/java/com/liferay/commerce/data/integration/talend/internal/TalendScheduledTaskExecutorService.java
Labels: ci:test - pending

#1799 COMMERCE-2537 now category friendly url translation may be added
  commerce-product-asset-categories-web/src/main/java/com/liferay/commerce/product/asset/categories/web/internal/portlet/action/EditAssetCategoryFriendlyURLMVCActionCommand.java
Labels: ci:test - pending
