Repository liferay/com-liferay-commerce, pull requests merged in 2019-01, with the labels that each got.

#346 COMMERCE-774 Fix suppression
  source-formatter-suppressions.xml
Labels: ci:test - pending

#340 COMMERCE-745 set translation based on locale
  commerce-address-web/src/main/resources/META-INF/resources/country/regions.jsp
  commerce-address-web/src/main/resources/META-INF/resources/view.jsp
  commerce-currency-web/src/main/resources/META-INF/resources/currency/currencies.jsp
  commerce-item-selector-web/src/main/resources/META-INF/resources/country_item_selector.jsp
  commerce-payment-web/src/main/resources/META-INF/resources/view.jsp
  commerce-product-measurement-unit-web/src/main/resources/META-INF/resources/view.jsp
  commerce-shipping-web/src/main/resources/META-INF/resources/view_shipping_methods.jsp
  commerce-tax-web/src/main/resources/META-INF/resources/view_tax_methods.jsp
Labels: ci:test - failure

#339 COMMERCE-771 Resolve Definition being set to draft every 3 publishes
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition/details.jsp
Labels: ci:test - failure

#341 COMMERCE-772 correct method signature
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java
Labels: ci:test - failure

#342 COMMERCE-773 Reorder methods inside deleteCPDefinition()
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java
Labels: ci:test - failure

#279 COMMERCE-740 Fixed virtual product's terms of use
  commerce-product-type-virtual-service/src/main/java/com/liferay/commerce/product/type/virtual/service/impl/CPDefinitionVirtualSettingLocalServiceImpl.java
Labels: ci:test - success

#363 COMMERCE-781 Ignore tests until APIO-310 is fixed
  commerce-data-integration-apio-test/src/testIntegration/java/com/liferay/commerce/data/integration/apio/resource/test/CPDefinitionNestedCollectionResourceTest.java
  commerce-data-integration-apio-test/src/testIntegration/java/com/liferay/commerce/data/integration/apio/resource/test/CPInstanceNestedCollectionResourceTest.java
  commerce-data-integration-apio-test/src/testIntegration/java/com/liferay/commerce/data/integration/apio/resource/test/CommerceAccountNestedCollectionResourceTest.java
  commerce-data-integration-apio-test/src/testIntegration/java/com/liferay/commerce/data/integration/apio/resource/test/CommerceAddressNestedCollectionResourceTest.java
  commerce-data-integration-apio-test/src/testIntegration/java/com/liferay/commerce/data/integration/apio/resource/test/CommercePriceListNestedCollectionResourceTest.java
  commerce-data-integration-apio-test/src/testIntegration/java/com/liferay/commerce/data/integration/apio/resource/test/CommerceUserCollectionResourceTest.java
Labels: ci:test - failure

#377 COMMERCE-820 Fixed commerce initializer importers
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/AssetCategoriesImporter.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/CPDefinitionsImporter.java
  commerce-initializer-util/src/main/java/com/liferay/commerce/initializer/util/internal/CPAttachmentFileEntryCreator.java
Labels: ci:test - pending

#373 COMMERCE-817 Make sure old urls will show the new product
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/AssetCategoryFriendlyURLResolver.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/ProductFriendlyURLResolver.java
Labels: ci:test - pending

#358 COMMERCE-738 Copy *.enabled=true properties from portal
  source-formatter.properties
Labels: ci:test - pending

#416 EMP-15 Add a Service Access Policy to ungate country/region APIs
  commerce-service/build.gradle
  commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceCountryLocalServiceImpl.java
  commerce-service/src/main/resources/com/liferay/commerce/internal/ungated-services.json
  commerce-service/src/main/resources/content/Language.properties
Labels: ci:test - failure

#325 COMMERCE-622 Fix upgrade process
  commerce-product-type-virtual-service/src/main/java/com/liferay/commerce/product/type/virtual/internal/upgrade/v1_1_0/CPDefinitionVirtualSettingUpgradeProcess.java
  commerce-product-type-virtual-service/src/main/resources/com/liferay/commerce/product/type/virtual/internal/upgrade/v1_1_0/dependencies/CPDefinitionVirtualSetting.sql
Labels: ci:test - failure

#436 COMMERCE-774 COMMERCE-778 Upgrade process for Accounts change
  commerce-service/bnd.bnd
  commerce-service/build.gradle
  commerce-service/src/main/java/com/liferay/commerce/internal/upgrade/CommerceUpgradeStepRegistrator.java
  commerce-service/src/main/java/com/liferay/commerce/internal/upgrade/v2_2_0/CommerceAccountUpgradeProcess.java
  commerce-service/src/main/java/com/liferay/commerce/internal/upgrade/v2_2_0/CommerceOrderUpgradeProcess.java
Labels: ci:test - failure

#444 COMMERCE-0 Source formatting for commerce-admin-*
  commerce-admin-web/src/main/java/com/liferay/commerce/admin/web/internal/portlet/EditCommerceAccountSettingsMVCActionCommand.java
  commerce-admin-web/src/main/java/com/liferay/commerce/admin/web/internal/util/AccountSettingsCommerceAdminModule.java
  commerce-admin-web/src/main/resources/META-INF/resources/configuration/edit_account_settings.jsp
  commerce-admin-web/src/main/resources/META-INF/resources/init.jsp
  commerce-lang/src/main/resources/content/Language.properties
Labels: ci:test - failure

#489 COMMERCE-872 Update JS dependency versions
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rels.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/toolbar.jsp
  commerce-product-options-web/src/main/resources/META-INF/resources/view.jsp
Labels: ci:test - failure

#498 COMMERCE-778 Fix failing test (7.1.x-next)
  commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
Labels: ci:test - success

#499 COMMERCE-778 Fix failing test (7.1.x)
  commerce-test/src/testIntegration/java/com/liferay/commerce/test/CommerceCheckoutTest.java
Labels: ci:test - success

#503 COMMERCE-921 Include src files in our releases
  .lfrbuild-release-src
Labels: ci:test - pending

#504 COMMERCE-921 Include src files in our releases (backport)
  .lfrbuild-release-src
Labels: ci:test - pending
