Repository liferay/com-liferay-commerce, pull requests merged in 2019-04, with the labels that each got.

#748 COMMERCE-1224 keep "active order" updated
  commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/AddressCommerceCheckoutStepUtil.java
  commerce-checkout-web/src/main/java/com/liferay/commerce/checkout/web/internal/util/ShippingAddressCommerceCheckoutStep.java
Labels: ci:test - success

#750 COMMERCE-1223 Fix css class name
  commerce-theme-minium/commerce-theme-minium/static-version/src/styles/overrides/_checkout-page.scss
Labels: ci:test - success

#752 COMMERCE-1226 Add handling for null cpInstance
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/wishlist/CommerceWishListResource.java
Labels: ci:test - success

#768 COMMERCE-1230 Add text field as a form field option
  commerce-product-api/src/main/java/com/liferay/commerce/product/configuration/CPOptionConfiguration.java
Labels: ci:test - success

#769 COMMERCE-1254 Get the definition from the link instead of display context
  commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_definition_link.jsp
Labels: ci:test - success

#763 COMMERCE-1248 Add titles for Country and Region selectors
  commerce-checkout-web/src/main/resources/META-INF/resources/checkout_step/address.jsp
Labels: ci:test - success

#759 COMMERCE-1245 Search by CommerceAccount model not User
  commerce-address-content-web/build.gradle
  commerce-address-content-web/src/main/java/com/liferay/commerce/address/content/web/internal/display/context/CommerceAddressDisplayContext.java
Labels: ci:test - success

#756 COMMERCE-1243 Use CProduct class when deleting friendlyUrl
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java
Labels: ci:test - success

#766 COMMERCE-1238 Remove checkbox from wishlist items since it's not useful
  commerce-wish-list-web/src/main/java/com/liferay/commerce/wish/list/web/internal/display/context/CommerceWishListDisplayContext.java
Labels: ci:test - success

#757 COMMERCE-1244 Fix getUniqueUrlTitles
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPDefinitionLocalServiceImpl.java
Labels: ci:test - success

#648 COMMERCE-1120 Rules should only be applied if active
  commerce-product-service/src/main/java/com/liferay/commerce/product/search/CPRuleIndexer.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPRuleLocalServiceImpl.java
Labels: ci:test - success

#751 COMMERCE-1228
  commerce-product-service/src/main/java/com/liferay/commerce/product/search/CPDefinitionIndexer.java
Labels: ci:test - success

#761 COMMERCE-1247 Use unit price instead of final price
  commerce-cart-content-web/src/main/resources/META-INF/resources/cart_mini/view.jsp
Labels: ci:test - success

#775 COMMERCE-1252 Wish list web needs one of the common lang keys now
  commerce-wish-list-web/build.gradle
Labels: ci:test - failure

#790 COMMERCE-1204 Make sure coupon add/delete works on first click
  commerce-discount-content-web/src/main/java/com/liferay/commerce/discount/content/web/internal/portlet/action/ApplyCommerceDiscountCouponCodeMVCActionCommand.java
  commerce-discount-content-web/src/main/resources/META-INF/resources/view.jsp
Labels: ci:test - failure

#789 COMMERCE-1207 Show discount info in Cart Summary
  commerce-cart-content-web/src/main/resources/META-INF/resources/cart_total/view.jsp
  commerce-initializer-breccia/src/main/resources/com/liferay/commerce/initializer/breccia/internal/dependencies/display_templates/BRECCIA_COMMERCE_CART_CONTENT_TOTAL.ftl
Labels: ci:test - failure

#787 COMMERCE-1252 Add dependency required for compileJSP
  commerce-wish-list-web/build.gradle
Labels: ci:test - failure

#785 COMMERCE-1212 Fix missed XSS vulnerabilities
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/frontend/CommerceAccountUserClayTable.java
  commerce-frontend-impl/src/main/java/com/liferay/commerce/frontend/internal/account/model/AccountUser.java
  commerce-initializer-breccia/src/main/resources/META-INF/resources/render/view.jsp
  commerce-product-options-web/src/main/resources/META-INF/resources/specification_option/details.jsp
  commerce-product-type-simple/src/main/resources/META-INF/resources/render/list_entry/compare_product.jsp
  commerce-theme-minium/commerce-theme-minium-impl/src/main/resources/META-INF/resources/render/view.jsp
Labels: ci:test - failure

#784 COMMERCE-1270 Filter results correctly (apply patch from Marco)
  commerce-order-content-web/src/main/resources/META-INF/resources/pending_orders/b2c/view.jsp
  commerce-order-content-web/src/main/resources/META-INF/resources/placed_orders/b2b/view.jsp
  commerce-order-content-web/src/main/resources/META-INF/resources/placed_orders/b2c/view.jsp
Labels: ci:test - failure

#804 COMMERCE-190 Expando icons
  commerce-account-web/src/main/java/com/liferay/commerce/account/web/internal/custom/attributes/CommerceAccountCustomAttributesDisplay.java
  commerce-discount-web/src/main/java/com/liferay/commerce/discount/web/internal/custom/attributes/CommerceDiscountCustomAttributesDisplay.java
  commerce-notification-web/src/main/java/com/liferay/commerce/notification/web/internal/custom/attributes/CommerceNotificationTemplateCustomAttributesDisplay.java
  commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/custom/attributes/CommerceOrderCustomAttributesDisplay.java
  commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/custom/attributes/CommerceOrderItemCustomAttributesDisplay.java
  commerce-price-list-web/src/main/java/com/liferay/commerce/price/list/web/internal/custom/attributes/CommercePriceEntryCustomAttributesDisplay.java
  commerce-price-list-web/src/main/java/com/liferay/commerce/price/list/web/internal/custom/attributes/CommercePriceListCustomAttributesDisplay.java
  commerce-price-list-web/src/main/java/com/liferay/commerce/price/list/web/internal/custom/attributes/CommerceTierPriceEntryCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPAttachmentFileEntryCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPDefinitionCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPDefinitionLinkCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPDefinitionOptionRelCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPDefinitionOptionValueRelCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPDefinitionSpecificationOptionValueCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPInstanceCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPRuleCustomAttributesDisplay.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/custom/attributes/CPSpecificationOptionCustomAttributesDisplay.java
  commerce-product-options-web/src/main/java/com/liferay/commerce/product/options/web/internal/custom/attributes/CPOptionCustomAttributesDisplay.java
  commerce-product-options-web/src/main/java/com/liferay/commerce/product/options/web/internal/custom/attributes/CPOptionValueCustomAttributesDisplay.java
  commerce-user-segment-web/src/main/java/com/liferay/commerce/user/segment/web/internal/custom/attributes/CommerceUserSegmentCriterionCustomAttributesDisplay.java
  commerce-user-segment-web/src/main/java/com/liferay/commerce/user/segment/web/internal/custom/attributes/CommerceUserSegmentEntryCustomAttributesDisplay.java
  commerce-warehouse-web/src/main/java/com/liferay/commerce/warehouse/web/internal/custom/attributes/CommerceWarehouseCustomAttributesDisplay.java
Labels: ci:test - pending

#812 COMMERCE-872 RELEASE-1441 Fix JS Dependencies
  commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rels.jsp
  commerce-product-definitions-web/src/main/resources/META-INF/resources/toolbar.jsp
  commerce-product-options-web/src/main/resources/META-INF/resources/view.jsp
  commerce-theme-minium/commerce-theme-minium-impl/src/main/java/com/liferay/commerce/theme/minium/internal/product/renderer/list/entry/MiniumCPContentListEntryRenderer.java
Labels: ci:test - success

#817 LPS-86806 Fix missing parentheses
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/filter/AsyncSupportedControlFilter.java
  commerce-openapi-core-impl/src/main/java/com/liferay/commerce/openapi/core/internal/interceptor/NestedWriteInterceptor.java
  commerce-openapi-core-impl/src/test/java/com/liferay/commerce/openapi/core/internal/util/request/MockHttpServletRequest.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/generator/ResourceGenerator.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/render/CPContentRendererRegistryImpl.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/render/list/CPContentListRendererRegistryImpl.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/render/list/entry/CPContentListEntryRendererRegistryImpl.java
Labels: ci:test - pending

#831 LPS-84119 Apply new SF rules
  commerce-cart-content-web/src/main/java/com/liferay/commerce/cart/content/web/internal/display/context/util/CommerceCartContentRequestHelper.java
  commerce-openapi-admin/src/main/java/com/liferay/commerce/openapi/admin/internal/resource/util/v2_0/OrderHelper.java
  commerce-openapi-util/src/main/java/com/liferay/commerce/openapi/util/importer/URLOpenApiReader.java
  commerce-openapi-util/src/test/java/com/liferay/commerce/openapi/util/generator/ResourceGeneratorTest.java
  commerce-order-web/src/main/java/com/liferay/commerce/order/web/internal/display/context/util/CommerceOrderRequestHelper.java
  commerce-payment-method-paypal/src/main/java/com/liferay/commerce/payment/method/paypal/internal/PayPalCommercePaymentMethod.java
  commerce-price-list-web/src/main/java/com/liferay/commerce/price/list/web/internal/portlet/action/EditCPInstanceCommercePriceEntryMVCActionCommand.java
  commerce-price-list-web/src/main/java/com/liferay/commerce/price/list/web/internal/portlet/action/EditCommercePriceEntryMVCActionCommand.java
  commerce-product-asset-categories-navigation-web/src/main/java/com/liferay/commerce/product/asset/categories/navigation/web/internal/display/context/CPAssetCategoriesNavigationDisplayContext.java
  commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/display/context/CPOptionFacetsDisplayContext.java
  commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/display/context/CPSearchResultsDisplayContext.java
  commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/display/context/CPPublisherDisplayContext.java
  commerce-product-definitions-web/src/main/java/com/liferay/commerce/product/definitions/web/internal/portlet/action/EditCPDefinitionOptionRelMVCActionCommand.java
  commerce-product-service/src/main/java/com/liferay/commerce/product/service/impl/CPAttachmentFileEntryLocalServiceImpl.java
  commerce-product-type-virtual-web/src/main/java/com/liferay/commerce/product/type/virtual/web/internal/display/context/CPDefinitionVirtualSettingDisplayContext.java
  commerce-product-type-virtual-web/src/main/java/com/liferay/commerce/product/type/virtual/web/internal/display/context/CommerceVirtualOrderItemEditDisplayContext.java
  commerce-shipment-content-web/src/main/java/com/liferay/commerce/shipment/content/web/internal/display/context/util/CommerceShipmentContentRequestHelper.java
  commerce-tax-engine-fixed-web/src/main/java/com/liferay/commerce/tax/engine/fixed/web/internal/display/context/BaseCommerceTaxFixedRateDisplayContext.java
  commerce-test/src/testIntegration/java/com/liferay/commerce/price/list/test/util/CommercePriceListTestUtil.java
  commerce-wish-list-web/src/main/java/com/liferay/commerce/wish/list/web/internal/display/context/util/CommerceWishListRequestHelper.java
Labels: ci:test - failure
